### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ObadaM** [thunder-project/thunder-factorization#3]
I am getting the following error when I try to install the thunder-factorization 

```
  Could not find a version that satisfies the requirement thunder-factorization (from versions: )
No matching distribution found for thunder-factorization
```

any idea why ?

**Comment by bainzo** [comment]
I had the same problem.

If you have git installed you can work around it by installing directly from the repository on github using,

```
pip install git+https://github.com/thunder-project/thunder-factorization.git
```

**Comment by jwittenbach** [comment]
Hi @bainzo and @ObadaM. We're still putting the finishing touches on `thunder-factorization` so we haven't published it yet, though we hope to very soon! In the meantime, it is mostly functional, so you can follow @bainzo's lead and clone the repo if you'd like to take it for a test ride. Definitely let us know if you find any issues.

**Comment by ObadaM** [comment]
@bainzo @jwittenbach it works for me, Thanks!

**Comment by talpay** [comment]
Maybe it's a good idea to remove the installation instructions with pip until it's actually published.....

**Comment by freeman-lab** [comment]
good call @talpay  just updated the README

**Comment by freeman-lab** [comment]
This can now be installed via `pip install thunder-factorization`, and the README is updated to say that.
